# .travis.yml
dist: precise
language: php
php:
  - '7.1'
  - nightly

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - mysql -e 'CREATE DATABASE orm_test;'

install: composer install --dev

after_script:
  - php vendor/bin/codacycoverage clover
