# .travis.yml
language: php
php:
  - '7.0.33'
  - '7.1'
  - '7.2'

git:
  depth: false

services:
  - mysql

addons:
  sonarcloud:
    organization: "csrdelft"

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - mysql -e 'CREATE DATABASE orm_test;'

install: composer install --dev

script:
  - php vendor/bin/phpunit
  - sonar-scanner

after_script:
  - php vendor/bin/codacycoverage clover
